# -*- coding: utf-8 -*-
"""chb_mit_delta_phi_pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1diGd1o3ies_6po5fuhkcqYC_alcVQBFv

# CHB-MIT DeltaPhi Test

Dieses Projekt untersucht, ob ein zusammengesetzter Marker (ΔΦ)
Veränderungen im EEG-Signal vor epileptischen Anfällen sichtbar machen kann.

Die zentrale Idee:
ΔΦ kombiniert Struktur (S), Information (I) und Kopplung (C)
zu einem gemeinsamen Signalzustand. Text fett markieren
"""

from google.colab import drive
drive.mount('/content/drive')

import os

base_path = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test"

folders = [
    base_path,
    f"{base_path}/data",
    f"{base_path}/data/chbmit",
    f"{base_path}/outputs",
    f"{base_path}/scripts"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Ordner angelegt:")
for folder in folders:
    print(folder)

import os

base_path = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test"

print("Projektordner gefunden:", os.path.exists(base_path))
print("Inhalt von MyDrive:")
print(os.listdir("/content/drive/MyDrive")[:20])

import os

patient_folder = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test/data/chbmit/chb01"
os.makedirs(patient_folder, exist_ok=True)

print("Ordner angelegt:")
print(patient_folder)

import zipfile

zip_file_path = "/content/drive/MyDrive/Tier2_OUT.zip"
extraction_dir = f"{base_path}/data/chbmit"

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_dir)

print(f"'{zip_file_path}' erfolgreich extrahiert nach '{extraction_dir}'")
print(f"Inhalt des Verzeichnisses '{extraction_dir}':\n{os.listdir(extraction_dir)}")

!pip install mne

file_path = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test/chb03_03.edf"

"""## Daten laden

Hier wird eine EEG-Datei aus dem CHB-MIT Datensatz geladen.

Ziel:
Das rohe Signal (Rohdaten) verfügbar machen, um es später in Zeitfenster zu zerlegen.
"""

import mne

file_path = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test/chb03_03.edf"

raw = mne.io.read_raw_edf(file_path, preload=True)

print(raw)

import mne

file_path = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test/chb03_03.edf"

raw = mne.io.read_raw_edf(file_path, preload=True)

print(raw)

print("Sampling Rate:", raw.info["sfreq"])
print("Anzahl Kanäle:", len(raw.ch_names))
print("Kanäle:", raw.ch_names)
print("Dauer in Sekunden:", raw.n_times / raw.info["sfreq"])

raw.plot(start=0, duration=20, n_channels=10, scalings='auto')

seizure_start = 432
seizure_end = 501

print("Anfall beginnt bei:", seizure_start, "Sekunden")
print("Anfall endet bei:", seizure_end, "Sekunden")

start_view = 380   # etwas vor dem Anfall
duration_view = 160  # bis etwas nach dem Anfall

raw.plot(start=start_view, duration=duration_view, n_channels=10, scalings='auto')

"""## Feature-Definition (S, I, C)

Wir beschreiben jedes Zeitfenster durch drei Dimensionen:

- **S (Struktur)**:
  Misst die geometrische Stabilität des Signals
  → basiert auf Varianz und Spannweite

- **I (Information)**:
  Shannon-Entropie
  → misst die Unordnung / Komplexität

- **C (Kopplung)**:
  Mittlere Korrelation zwischen Kanälen
  → misst Synchronisation im Gehirn

Diese drei Größen bilden zusammen einen Zustand des Systems.
"""

import numpy as np

sfreq = raw.info["sfreq"]  # 256 Hz
window_size = int(10 * sfreq)  # 10 Sekunden

data = raw.get_data()

windows = []
times = []

for start in range(0, data.shape[1] - window_size, window_size):
    end = start + window_size
    window = data[:, start:end]

    windows.append(window)
    times.append(start / sfreq)

print("Anzahl Fenster:", len(windows))

import numpy as np

sfreq = raw.info["sfreq"]  # 256 Hz
window_size = int(10 * sfreq)  # 10 Sekunden

data = raw.get_data()

windows = []
times = []

for start in range(0, data.shape[1] - window_size, window_size):
    end = start + window_size
    window = data[:, start:end]

    windows.append(window)
    times.append(start / sfreq)

print("Anzahl Fenster:", len(windows))

import numpy as np
import pandas as pd

sfreq = raw.info["sfreq"]   # sollte 256 sein
duration_sec = raw.n_times / sfreq
window_sec = 10

windows = []
for start in np.arange(0, duration_sec, window_sec):
    end = min(start + window_sec, duration_sec)
    windows.append((float(start), float(end)))

df_windows = pd.DataFrame(windows, columns=["win_start_s", "win_end_s"])
print("Anzahl Fenster:", len(df_windows))
df_windows.head()

seizure_start = 432
seizure_end = 501

SOP = 30 * 60   # 30 Minuten
SPH = 5 * 60    # 5 Minuten
POST = 30 * 60  # 30 Minuten

def label_window(row):
    center = (row["win_start_s"] + row["win_end_s"]) / 2

    # ictal
    if seizure_start <= center < seizure_end:
        return "ictal"

    # preictal: 30 bis 5 Minuten vor Anfall
    if (seizure_start - SOP) <= center < (seizure_start - SPH):
        return "preictal"

    # postictal ausschließen
    if seizure_end <= center < (seizure_end + POST):
        return "exclude"

    # Rest
    return "interictal_candidate"

df_windows["label"] = df_windows.apply(label_window, axis=1)

print(df_windows["label"].value_counts())
df_windows.head(15)

df_windows[(df_windows["win_start_s"] >= 350) & (df_windows["win_end_s"] <= 550)]

df_use = df_windows[df_windows["label"].isin(["preictal", "ictal", "interictal_candidate"])].copy()

print(df_use["label"].value_counts())
df_use.head()

import numpy as np

sfreq = raw.info["sfreq"]

window_arrays = []

for _, row in df_use.iterrows():
    start_sample = int(row["win_start_s"] * sfreq)
    end_sample = int(row["win_end_s"] * sfreq)
    segment = raw.get_data(start=start_sample, stop=end_sample)

    window_arrays.append({
        "win_start_s": row["win_start_s"],
        "win_end_s": row["win_end_s"],
        "label": row["label"],
        "data": segment
    })

print("Anzahl ausgeschnittener Fenster:", len(window_arrays))
print("Form des ersten Fensters:", window_arrays[0]["data"].shape)

import numpy as np
import pandas as pd

features = []

for w in window_arrays:
    data = w["data"]  # shape: (channels, samples)

    # 1. mittlere absolute Amplitude
    amp = np.mean(np.abs(data))

    # 2. Varianz
    var = np.var(data)

    # 3. mittlere Kanal-Korrelation
    corr_matrix = np.corrcoef(data)
    corr_mean = np.mean(np.abs(corr_matrix))

    features.append({
        "win_start_s": w["win_start_s"],
        "label": w["label"],
        "amp": amp,
        "var": var,
        "corr": corr_mean
    })

df_feat = pd.DataFrame(features)

print(df_feat.head())
print(df_feat["label"].value_counts())

df_feat.groupby("label")[["amp", "var", "corr"]].mean()

import matplotlib.pyplot as plt

for feature in ["amp", "var", "corr"]:
    plt.figure()
    for label in df_feat["label"].unique():
        subset = df_feat[df_feat["label"] == label]
        plt.hist(subset[feature], bins=30, alpha=0.5, label=label)
    plt.title(feature)
    plt.legend()
    plt.show()

df_feat.groupby("label").mean()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -----------------------------
# 1) Hilfsfunktionen
# -----------------------------
def shannon_entropy_1d(x, bins=64):
    x = np.asarray(x).ravel()
    hist, _ = np.histogram(x, bins=bins, density=True)
    hist = hist[hist > 0]
    if len(hist) == 0:
        return 0.0
    p = hist / hist.sum()
    return -np.sum(p * np.log(p + 1e-12))

def compute_window_features(window_data):
    """
    window_data: shape (n_channels, n_samples)
    Gibt einfache, robuste S/I/C-Features zurück.
    """

    # --------
    # S = Struktur / Signalgeometrie
    # Hier: Mittelwert aus Kanal-Varianzen + mittlere Spannweite
    # --------
    channel_vars = np.var(window_data, axis=1)
    channel_ranges = np.ptp(window_data, axis=1)  # max-min je Kanal
    S = 0.5 * np.mean(channel_vars) + 0.5 * np.mean(channel_ranges)

    # --------
    # I = Information / Entropie
    # Shannon-Entropie pro Kanal, dann Mittelwert
    # --------
    entropies = [shannon_entropy_1d(ch, bins=64) for ch in window_data]
    I = np.mean(entropies)

    # --------
    # C = Kohärenz / Kopplung
    # Hier: mittlere absolute Kanal-Korrelation (ohne Diagonale)
    # --------
    corr = np.corrcoef(window_data)
    corr = np.nan_to_num(corr, nan=0.0)
    upper = corr[np.triu_indices_from(corr, k=1)]
    C = np.mean(np.abs(upper))

    return S, I, C

# -----------------------------
# 2) Features für alle Fenster berechnen
# -----------------------------
rows = []

for item in window_arrays:
    S, I, C = compute_window_features(item["data"])
    rows.append({
        "win_start_s": item["win_start_s"],
        "win_end_s": item["win_end_s"],
        "label": item["label"],
        "S": S,
        "I": I,
        "C": C
    })

df_feat = pd.DataFrame(rows)

print("Feature-Tabelle erstellt:")
print(df_feat.head())

# -----------------------------
# 3) Baseline nur aus interictal_candidate
# -----------------------------
baseline_df = df_feat[df_feat["label"] == "interictal_candidate"].copy()

baseline_S = baseline_df["S"].mean()
baseline_I = baseline_df["I"].mean()
baseline_C = baseline_df["C"].mean()

print("\nBaseline:")
print("S_baseline =", baseline_S)
print("I_baseline =", baseline_I)
print("C_baseline =", baseline_C)

# -----------------------------
# 4) Delta-Werte und ΔΦ
# -----------------------------
ALPHA = 0.40
BETA  = 0.35
GAMMA = 0.25

df_feat["dS"] = df_feat["S"] - baseline_S
df_feat["dI"] = df_feat["I"] - baseline_I
df_feat["dC"] = df_feat["C"] - baseline_C

df_feat["DeltaPhi"] = (
    ALPHA * np.abs(df_feat["dS"]) +
    BETA  * np.abs(df_feat["dI"]) +
    GAMMA * np.abs(df_feat["dC"])
)

print("\nDeltaPhi berechnet:")
print(df_feat[["win_start_s", "win_end_s", "label", "DeltaPhi"]].head())

# -----------------------------
# 5) Einfache Statistik nach Label
# -----------------------------
summary = df_feat.groupby("label")["DeltaPhi"].agg(["count", "mean", "std", "median", "max"])
print("\nDeltaPhi nach Label:")
print(summary)

# -----------------------------
# 6) Plot über Zeit
# -----------------------------
df_feat["center_s"] = 0.5 * (df_feat["win_start_s"] + df_feat["win_end_s"])

plt.figure(figsize=(14, 6))
plt.plot(df_feat["center_s"], df_feat["DeltaPhi"], marker="o", linestyle="-", label="ΔΦ")

# Anfallsbereich markieren
plt.axvspan(seizure_start, seizure_end, alpha=0.25, label="Ictal window")

# Farben je Label optional markieren
for lbl, color in [("interictal_candidate", "blue"), ("preictal", "orange"), ("ictal", "red")]:
    sub = df_feat[df_feat["label"] == lbl]
    plt.scatter(sub["center_s"], sub["DeltaPhi"], label=lbl)

plt.xlabel("Zeit (Sekunden)")
plt.ylabel("ΔΦ")
plt.title("ΔΦ über die Zeit (CHB-MIT Fenster)")
plt.legend()
plt.grid(True)
plt.show()

# -----------------------------
# 7) CSV speichern
# -----------------------------
save_path = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test/outputs/delta_phi_features_chb03_03.csv"
df_feat.to_csv(save_path, index=False)
print(f"\nGespeichert unter: {save_path}")

df_feat["DeltaPhi_smooth"] = df_feat["DeltaPhi"].rolling(5).mean()

"""## Erste Beobachtungen

Hier vergleichen wir ΔΦ zwischen:

- interictal (normal)
- preictal (vor dem Anfall)
- ictal (Anfall)

Interpretation:

Wenn ΔΦ im preictal Bereich steigt,
kann das ein Hinweis auf eine bevorstehende Veränderung sein.

Wenn kein klarer Unterschied sichtbar ist:

➡️ Das ist ebenfalls wichtig:
Es zeigt, dass das Signal subtiler ist als erwartet
oder dass zusätzliche Faktoren berücksichtigt werden müssen.
"""

# statt 30–5 min
# zB:
SOP = 10 * 60
SPH = 1 * 60

# =========================================
# STEP 2 – SMOOTHING + BESSERE AUSWERTUNG
# =========================================

# -----------------------------
# 1) ΔΦ glätten (Memory-Effekt)
# -----------------------------
window_smooth = 5  # 5 Fenster = 50 Sekunden

df_feat["DeltaPhi_smooth"] = df_feat["DeltaPhi"].rolling(window_smooth, min_periods=1).mean()

# -----------------------------
# 2) Fokus auf Preictal vs Interictal
# -----------------------------
df_eval = df_feat[df_feat["label"].isin(["preictal", "interictal_candidate"])].copy()

# Label binär machen
df_eval["y"] = (df_eval["label"] == "preictal").astype(int)

# -----------------------------
# 3) Schwellen-Test (einfacher Klassifikator)
# -----------------------------
thresholds = np.linspace(df_eval["DeltaPhi_smooth"].min(), df_eval["DeltaPhi_smooth"].max(), 50)

results = []

for t in thresholds:
    preds = (df_eval["DeltaPhi_smooth"] > t).astype(int)

    TP = np.sum((preds == 1) & (df_eval["y"] == 1))
    TN = np.sum((preds == 0) & (df_eval["y"] == 0))
    FP = np.sum((preds == 1) & (df_eval["y"] == 0))
    FN = np.sum((preds == 0) & (df_eval["y"] == 1))

    sensitivity = TP / (TP + FN + 1e-9)
    specificity = TN / (TN + FP + 1e-9)

    results.append((t, sensitivity, specificity))

df_results = pd.DataFrame(results, columns=["threshold", "sensitivity", "specificity"])

# -----------------------------
# 4) Besten Threshold finden
# -----------------------------
df_results["score"] = df_results["sensitivity"] + df_results["specificity"]

best = df_results.loc[df_results["score"].idxmax()]

print("\nBESTER THRESHOLD:")
print(best)

# -----------------------------
# 5) Plot – ROC-artig
# -----------------------------
plt.figure(figsize=(6,6))
plt.plot(1 - df_results["specificity"], df_results["sensitivity"], marker="o")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC-ähnliche Kurve (ΔΦ smooth)")
plt.grid(True)
plt.show()

# -----------------------------
# 6) Zeitplot mit smooth ΔΦ
# -----------------------------
plt.figure(figsize=(14,6))

plt.plot(df_feat["center_s"], df_feat["DeltaPhi"], alpha=0.3, label="ΔΦ raw")
plt.plot(df_feat["center_s"], df_feat["DeltaPhi_smooth"], linewidth=2, label="ΔΦ smooth")

plt.axvspan(seizure_start, seizure_end, alpha=0.25, label="Ictal")

plt.xlabel("Zeit (Sekunden)")
plt.ylabel("ΔΦ")
plt.title("ΔΦ mit Memory (geglättet)")
plt.legend()
plt.grid(True)
plt.show()

"""## Persönliche Interpretation

Dieses Modell ist kein fertiges Diagnosewerkzeug,
sondern ein Versuch, ein komplexes biologisches System
in eine messbare Form zu bringen.

Das Ziel ist nicht sofortige Perfektion,
sondern schrittweises Verständnis.

Jede Abweichung ist ein Signal.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mne

# =========================================
# IDENTISCHE PIPELINE ALS FUNKTION
# =========================================

def shannon_entropy_1d(x, bins=64):
    x = np.asarray(x).ravel()
    hist, _ = np.histogram(x, bins=bins, density=True)
    hist = hist[hist > 0]
    if len(hist) == 0:
        return 0.0
    p = hist / hist.sum()
    return -np.sum(p * np.log(p + 1e-12))

def compute_window_features(window_data):
    # exakt gleiche Feature-Logik
    channel_vars = np.var(window_data, axis=1)
    channel_ranges = np.ptp(window_data, axis=1)
    S = 0.5 * np.mean(channel_vars) + 0.5 * np.mean(channel_ranges)

    entropies = [shannon_entropy_1d(ch, bins=64) for ch in window_data]
    I = np.mean(entropies)

    corr = np.corrcoef(window_data)
    corr = np.nan_to_num(corr, nan=0.0)
    upper = corr[np.triu_indices_from(corr, k=1)]
    C = np.mean(np.abs(upper))

    return S, I, C

def run_same_pipeline(edf_path, seizure_start, seizure_end, file_tag):
    raw = mne.io.read_raw_edf(edf_path, preload=True, verbose=False)

    sfreq = raw.info["sfreq"]
    duration_sec = raw.n_times / sfreq
    window_sec = 10

    # -----------------------------
    # 1) Fenster
    # -----------------------------
    windows = []
    for start in np.arange(0, duration_sec, window_sec):
        end = min(start + window_sec, duration_sec)
        windows.append((float(start), float(end)))

    df_windows = pd.DataFrame(windows, columns=["win_start_s", "win_end_s"])

    # -----------------------------
    # 2) Labeling (EXAKT gleich)
    # -----------------------------
    SOP = 30 * 60   # 30 Minuten
    SPH = 5 * 60    # 5 Minuten
    POST = 30 * 60  # 30 Minuten

    def label_window(row):
        center = (row["win_start_s"] + row["win_end_s"]) / 2

        if seizure_start <= center < seizure_end:
            return "ictal"

        if (seizure_start - SOP) <= center < (seizure_start - SPH):
            return "preictal"

        if seizure_end <= center < (seizure_end + POST):
            return "exclude"

        return "interictal_candidate"

    df_windows["label"] = df_windows.apply(label_window, axis=1)
    df_use = df_windows[df_windows["label"].isin(["preictal", "ictal", "interictal_candidate"])].copy()

    # -----------------------------
    # 3) Segmente ausschneiden
    # -----------------------------
    window_arrays = []

    for _, row in df_use.iterrows():
        start_sample = int(row["win_start_s"] * sfreq)
        end_sample = int(row["win_end_s"] * sfreq)
        segment = raw.get_data(start=start_sample, stop=end_sample)

        window_arrays.append({
            "win_start_s": row["win_start_s"],
            "win_end_s": row["win_end_s"],
            "label": row["label"],
            "data": segment
        })

    # -----------------------------
    # 4) S / I / C berechnen
    # -----------------------------
    rows = []

    for item in window_arrays:
        S, I, C = compute_window_features(item["data"])
        rows.append({
            "file": file_tag,
            "win_start_s": item["win_start_s"],
            "win_end_s": item["win_end_s"],
            "label": item["label"],
            "S": S,
            "I": I,
            "C": C
        })

    df_feat = pd.DataFrame(rows)

    # -----------------------------
    # 5) Baseline aus interictal_candidate
    # -----------------------------
    baseline_df = df_feat[df_feat["label"] == "interictal_candidate"].copy()

    baseline_S = baseline_df["S"].mean()
    baseline_I = baseline_df["I"].mean()
    baseline_C = baseline_df["C"].mean()

    # -----------------------------
    # 6) ΔΦ (EXAKT gleich)
    # -----------------------------
    ALPHA = 0.40
    BETA  = 0.35
    GAMMA = 0.25

    df_feat["dS"] = df_feat["S"] - baseline_S
    df_feat["dI"] = df_feat["I"] - baseline_I
    df_feat["dC"] = df_feat["C"] - baseline_C

    df_feat["DeltaPhi"] = (
        ALPHA * np.abs(df_feat["dS"]) +
        BETA  * np.abs(df_feat["dI"]) +
        GAMMA * np.abs(df_feat["dC"])
    )

    # -----------------------------
    # 7) Glättung / Memory (EXAKT gleich)
    # -----------------------------
    window_smooth = 5
    df_feat["DeltaPhi_smooth"] = df_feat["DeltaPhi"].rolling(window_smooth, min_periods=1).mean()

    # -----------------------------
    # 8) Zeitachse
    # -----------------------------
    df_feat["center_s"] = 0.5 * (df_feat["win_start_s"] + df_feat["win_end_s"])

    # -----------------------------
    # 9) Label-Mittelwerte
    # -----------------------------
    summary = df_feat.groupby("label")["DeltaPhi"].agg(["count", "mean", "std", "median", "max"])

    # -----------------------------
    # 10) Threshold / ROC-artig
    # -----------------------------
    df_eval = df_feat[df_feat["label"].isin(["preictal", "interictal_candidate"])].copy()
    df_eval["y"] = (df_eval["label"] == "preictal").astype(int)

    thresholds = np.linspace(df_eval["DeltaPhi_smooth"].min(), df_eval["DeltaPhi_smooth"].max(), 50)
    results = []

    for t in thresholds:
        preds = (df_eval["DeltaPhi_smooth"] > t).astype(int)

        TP = np.sum((preds == 1) & (df_eval["y"] == 1))
        TN = np.sum((preds == 0) & (df_eval["y"] == 0))
        FP = np.sum((preds == 1) & (df_eval["y"] == 0))
        FN = np.sum((preds == 0) & (df_eval["y"] == 1))

        sensitivity = TP / (TP + FN + 1e-9)
        specificity = TN / (TN + FP + 1e-9)

        results.append((t, sensitivity, specificity))

    df_results = pd.DataFrame(results, columns=["threshold", "sensitivity", "specificity"])
    df_results["score"] = df_results["sensitivity"] + df_results["specificity"]
    best = df_results.loc[df_results["score"].idxmax()]

    # -----------------------------
    # 11) Plots
    # -----------------------------
    plt.figure(figsize=(14, 6))
    plt.plot(df_feat["center_s"], df_feat["DeltaPhi"], marker="o", linestyle="-", label="ΔΦ")
    plt.axvspan(seizure_start, seizure_end, alpha=0.25, label="Ictal window")
    plt.xlabel("Zeit (Sekunden)")
    plt.ylabel("ΔΦ")
    plt.title(f"ΔΦ über die Zeit ({file_tag})")
    plt.legend()
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(14, 6))
    plt.plot(df_feat["center_s"], df_feat["DeltaPhi"], alpha=0.3, label="ΔΦ raw")
    plt.plot(df_feat["center_s"], df_feat["DeltaPhi_smooth"], linewidth=2, label="ΔΦ smooth")
    plt.axvspan(seizure_start, seizure_end, alpha=0.25, label="Ictal")
    plt.xlabel("Zeit (Sekunden)")
    plt.ylabel("ΔΦ")
    plt.title(f"ΔΦ mit Memory/Glättung ({file_tag})")
    plt.legend()
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(6, 6))
    plt.plot(1 - df_results["specificity"], df_results["sensitivity"], marker="o")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(f"ROC-ähnliche Kurve ({file_tag})")
    plt.grid(True)
    plt.show()

    # -----------------------------
    # 12) Ausgabe
    # -----------------------------
    print(f"\n===== {file_tag} =====")
    print("Fenster pro Label:")
    print(df_feat["label"].value_counts())
    print("\nMittelwerte pro Label:")
    print(summary)
    print("\nBester Threshold:")
    print(best)

    return df_feat, summary, df_results, best


# =========================================
# CHB03_03 NOCHMAL SAUBER DURCH DIE FUNKTION
# =========================================
edf_03 = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test/chb03_03.edf"
seizure_start_03 = 432
seizure_end_03 = 501

df_feat_03, summary_03, roc_03, best_03 = run_same_pipeline(
    edf_path=edf_03,
    seizure_start=seizure_start_03,
    seizure_end=seizure_end_03,
    file_tag="chb03_03"
)

# =========================================
# CHB03_04 – HIER NUR DIE KORREKTEN ZEITEN EINTRAGEN
# =========================================
edf_04 = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test/chb03_04.edf"

# HIER DIE RICHTIGEN ANFALLSZEITEN FÜR chb03_04 EINTRAGEN:
seizure_start_04 = 2162
seizure_end_04 = 2214

df_feat_04, summary_04, roc_04, best_04 = run_same_pipeline(
    edf_path=edf_04,
    seizure_start=seizure_start_04,
    seizure_end=seizure_end_04,
    file_tag="chb03_04"
)

print("\n========== VERGLEICH MITTELWERTE ==========")
print("\nchb03_03")
print(summary_03)

print("\nchb03_04")
print(summary_04)

print("\n========== VERGLEICH BESTER THRESHOLD ==========")
print("\nchb03_03")
print(best_03)

print("\nchb03_04")
print(best_04)

# =========================================
# COMBINED ANALYSIS
# =========================================
df_combined = pd.concat([df_feat_03, df_feat_04], ignore_index=True)

summary_combined = df_combined.groupby("label")["DeltaPhi"].agg(
    ["count", "mean", "std", "median", "max"]
)

print("\n===== COMBINED MITTELWERTE PRO LABEL =====")
print(summary_combined)

df_eval_combined = df_combined[df_combined["label"].isin(["preictal", "interictal_candidate"])].copy()
df_eval_combined["y"] = (df_eval_combined["label"] == "preictal").astype(int)

thresholds = np.linspace(
    df_eval_combined["DeltaPhi_smooth"].min(),
    df_eval_combined["DeltaPhi_smooth"].max(),
    60
)

results_combined = []

for t in thresholds:
    preds = (df_eval_combined["DeltaPhi_smooth"] > t).astype(int)

    TP = np.sum((preds == 1) & (df_eval_combined["y"] == 1))
    TN = np.sum((preds == 0) & (df_eval_combined["y"] == 0))
    FP = np.sum((preds == 1) & (df_eval_combined["y"] == 0))
    FN = np.sum((preds == 0) & (df_eval_combined["y"] == 1))

    sensitivity = TP / (TP + FN + 1e-9)
    specificity = TN / (TN + FP + 1e-9)

    results_combined.append((t, sensitivity, specificity))

roc_combined = pd.DataFrame(results_combined, columns=["threshold", "sensitivity", "specificity"])
roc_combined["score"] = roc_combined["sensitivity"] + roc_combined["specificity"]
best_combined = roc_combined.loc[roc_combined["score"].idxmax()]

print("\n===== BESTER COMBINED THRESHOLD =====")
print(best_combined)

seizure_start_04 = 2162
seizure_end_04 = 2214

edf_04 = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test/chb03_04.edf"

seizure_start_04 = 2162
seizure_end_04 = 2214

df_feat_04, summary_04, roc_04, best_04 = run_same_pipeline(
    edf_path=edf_04,
    seizure_start=seizure_start_04,
    seizure_end=seizure_end_04,
    file_tag="chb03_04"
)

print("\n========== VERGLEICH MITTELWERTE ==========")
print("\nchb03_03")
print(summary_03)

print("\nchb03_04")
print(summary_04)

print("\n========== VERGLEICH BESTER THRESHOLD ==========")
print("\nchb03_03")
print(best_03)

print("\nchb03_04")
print(best_04)

# =========================================
# COMBINED ANALYSIS: chb03_03 + chb03_04
# =========================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# 1) Beide DataFrames zusammenführen
# -----------------------------
df_combined = pd.concat([df_feat_03, df_feat_04], ignore_index=True)

print("Gesamtzahl Fenster:", len(df_combined))
print("\nFenster pro Datei und Label:")
print(df_combined.groupby(["file", "label"]).size())

# -----------------------------
# 2) Gesamt-Mittelwerte pro Label
# -----------------------------
summary_combined = df_combined.groupby("label")["DeltaPhi"].agg(
    ["count", "mean", "std", "median", "max"]
)

print("\n===== COMBINED MITTELWERTE PRO LABEL =====")
print(summary_combined)

# -----------------------------
# 3) Combined Threshold / ROC-artig
#    preictal vs interictal_candidate
# -----------------------------
df_eval_combined = df_combined[df_combined["label"].isin(["preictal", "interictal_candidate"])].copy()
df_eval_combined["y"] = (df_eval_combined["label"] == "preictal").astype(int)

thresholds = np.linspace(
    df_eval_combined["DeltaPhi_smooth"].min(),
    df_eval_combined["DeltaPhi_smooth"].max(),
    60
)

results_combined = []

for t in thresholds:
    preds = (df_eval_combined["DeltaPhi_smooth"] > t).astype(int)

    TP = np.sum((preds == 1) & (df_eval_combined["y"] == 1))
    TN = np.sum((preds == 0) & (df_eval_combined["y"] == 0))
    FP = np.sum((preds == 1) & (df_eval_combined["y"] == 0))
    FN = np.sum((preds == 0) & (df_eval_combined["y"] == 1))

    sensitivity = TP / (TP + FN + 1e-9)
    specificity = TN / (TN + FP + 1e-9)

    results_combined.append((t, sensitivity, specificity))

roc_combined = pd.DataFrame(
    results_combined,
    columns=["threshold", "sensitivity", "specificity"]
)

roc_combined["score"] = roc_combined["sensitivity"] + roc_combined["specificity"]

best_combined = roc_combined.loc[roc_combined["score"].idxmax()]

print("\n===== BESTER COMBINED THRESHOLD =====")
print(best_combined)

# -----------------------------
# 4) ROC-artiger Plot
# -----------------------------
plt.figure(figsize=(6, 6))
plt.plot(1 - roc_combined["specificity"], roc_combined["sensitivity"], marker="o")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC-ähnliche Kurve (combined)")
plt.grid(True)
plt.show()

# -----------------------------
# 5) Combined Vergleichsplot:
#    ΔΦ raw nach Datei
# -----------------------------
plt.figure(figsize=(14, 6))

for file_name, sub in df_combined.groupby("file"):
    sub = sub.sort_values("center_s")
    plt.plot(sub["center_s"], sub["DeltaPhi"], marker="o", linestyle="-", label=f"{file_name} raw")

plt.xlabel("Zeit (Sekunden)")
plt.ylabel("ΔΦ")
plt.title("ΔΦ raw – Vergleich beider Dateien")
plt.legend()
plt.grid(True)
plt.show()

# -----------------------------
# 6) Combined Vergleichsplot:
#    ΔΦ smooth nach Datei
# -----------------------------
plt.figure(figsize=(14, 6))

for file_name, sub in df_combined.groupby("file"):
    sub = sub.sort_values("center_s")
    plt.plot(sub["center_s"], sub["DeltaPhi_smooth"], linewidth=2, label=f"{file_name} smooth")

plt.xlabel("Zeit (Sekunden)")
plt.ylabel("ΔΦ smooth")
plt.title("ΔΦ smooth – Vergleich beider Dateien")
plt.legend()
plt.grid(True)
plt.show()

# -----------------------------
# 7) CSV speichern
# -----------------------------
save_combined_csv = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test/outputs/combined_delta_phi_chb03_03_04.csv"
df_combined.to_csv(save_combined_csv, index=False)

print("\nCombined CSV gespeichert unter:")
print(save_combined_csv)

print("\n========== FINALER KURZVERGLEICH ==========")

print("\nchb03_03")
print(summary_03)
print(best_03)

print("\nchb03_04")
print(summary_04)
print(best_04)

print("\ncombined")
print(summary_combined)
print(best_combined)

# =========================================
# PREICTAL-ANALYSE NACH ABSTAND ZUM ANFALL
# =========================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -----------------------------
# 1) Hilfsfunktion:
# Abstand eines Fensters zum Anfall berechnen
# -----------------------------
def add_minutes_before_seizure(df, seizure_start, file_name):
    df = df.copy()
    df["file"] = file_name
    df["center_s"] = 0.5 * (df["win_start_s"] + df["win_end_s"])

    # nur für preictal sinnvoll
    df["minutes_before_seizure"] = (seizure_start - df["center_s"]) / 60.0
    return df

# Für chb03_03 und chb03_04 die Minuten-bis-Anfall ergänzen
df_pre_03 = add_minutes_before_seizure(df_feat_03, seizure_start_03, "chb03_03")
df_pre_04 = add_minutes_before_seizure(df_feat_04, seizure_start_04, "chb03_04")

# Nur preictal + interictal behalten
df_pre_03 = df_pre_03[df_pre_03["label"].isin(["preictal", "interictal_candidate"])].copy()
df_pre_04 = df_pre_04[df_pre_04["label"].isin(["preictal", "interictal_candidate"])].copy()

# Zusammenführen
df_pre_combined = pd.concat([df_pre_03, df_pre_04], ignore_index=True)

print("Größe combined preictal/interictal:", len(df_pre_combined))
print(df_pre_combined["label"].value_counts())

# =========================================
# PREICTAL-BINS DEFINIEREN
# =========================================

# Preictal-Bereiche:
# 25-30, 20-25, 15-20, 10-15, 5-10 Minuten vor dem Anfall
bins = [5, 10, 15, 20, 25, 30]
labels = ["5-10", "10-15", "15-20", "20-25", "25-30"]

df_pre_combined["preictal_bin"] = pd.cut(
    df_pre_combined["minutes_before_seizure"],
    bins=bins,
    labels=labels,
    right=False
)

# Nur preictal bekommt Bins, interictal bleibt leer
df_pre_only = df_pre_combined[df_pre_combined["label"] == "preictal"].copy()

print("\nPreictal-Bins:")
print(df_pre_only["preictal_bin"].value_counts().sort_index())

# =========================================
# MITTELWERTE PRO PREICTAL-BIN
# =========================================

interictal_mean = df_pre_combined[df_pre_combined["label"] == "interictal_candidate"]["DeltaPhi"].mean()
interictal_smooth_mean = df_pre_combined[df_pre_combined["label"] == "interictal_candidate"]["DeltaPhi_smooth"].mean()

summary_pre_bins = df_pre_only.groupby("preictal_bin")[["DeltaPhi", "DeltaPhi_smooth"]].agg(
    ["count", "mean", "std", "median", "max"]
)

print("\n===== PREICTAL-BINS: DELTAPHI =====")
print(summary_pre_bins)

print("\nInterictal mean DeltaPhi:", interictal_mean)
print("Interictal mean DeltaPhi_smooth:", interictal_smooth_mean)

# =========================================
# PLOT: PREICTAL-BINS VS INTERICTAL
# =========================================

pre_bin_means = df_pre_only.groupby("preictal_bin")["DeltaPhi"].mean().reindex(labels)
pre_bin_smooth_means = df_pre_only.groupby("preictal_bin")["DeltaPhi_smooth"].mean().reindex(labels)

plt.figure(figsize=(10, 5))
plt.plot(labels, pre_bin_means.values, marker="o", label="Preictal mean ΔΦ")
plt.axhline(interictal_mean, linestyle="--", label="Interictal mean ΔΦ")
plt.xlabel("Minuten vor Anfall")
plt.ylabel("ΔΦ")
plt.title("Preictal ΔΦ nach Abstand zum Anfall")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 5))
plt.plot(labels, pre_bin_smooth_means.values, marker="o", label="Preictal mean ΔΦ smooth")
plt.axhline(interictal_smooth_mean, linestyle="--", label="Interictal mean ΔΦ smooth")
plt.xlabel("Minuten vor Anfall")
plt.ylabel("ΔΦ smooth")
plt.title("Preictal ΔΦ smooth nach Abstand zum Anfall")
plt.legend()
plt.grid(True)
plt.show()

# =========================================
# LATE PREICTAL (5-10 MIN) VS INTERICTAL
# =========================================

df_late = df_pre_combined[
    (df_pre_combined["label"] == "interictal_candidate") |
    ((df_pre_combined["label"] == "preictal") & (df_pre_combined["preictal_bin"] == "5-10"))
].copy()

df_late["y"] = (
    (df_late["label"] == "preictal") & (df_late["preictal_bin"] == "5-10")
).astype(int)

print("\nLate-preictal vs interictal:")
print(df_late["y"].value_counts())

thresholds_late = np.linspace(df_late["DeltaPhi_smooth"].min(), df_late["DeltaPhi_smooth"].max(), 50)

results_late = []

for t in thresholds_late:
    preds = (df_late["DeltaPhi_smooth"] > t).astype(int)

    TP = np.sum((preds == 1) & (df_late["y"] == 1))
    TN = np.sum((preds == 0) & (df_late["y"] == 0))
    FP = np.sum((preds == 1) & (df_late["y"] == 0))
    FN = np.sum((preds == 0) & (df_late["y"] == 1))

    sensitivity = TP / (TP + FN + 1e-9)
    specificity = TN / (TN + FP + 1e-9)

    results_late.append((t, sensitivity, specificity))

df_late_results = pd.DataFrame(results_late, columns=["threshold", "sensitivity", "specificity"])
df_late_results["score"] = df_late_results["sensitivity"] + df_late_results["specificity"]

best_late = df_late_results.loc[df_late_results["score"].idxmax()]

print("\n===== BESTER THRESHOLD: LATE PREICTAL (5-10) VS INTERICTAL =====")
print(best_late)

plt.figure(figsize=(6, 6))
plt.plot(1 - df_late_results["specificity"], df_late_results["sensitivity"], marker="o")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC-ähnliche Kurve: Late preictal (5-10) vs interictal")
plt.grid(True)
plt.show()

print("\n===== PREICTAL-BINS: DELTAPHI =====")
print(summary_pre_bins)

print("\nInterictal mean DeltaPhi:", interictal_mean)
print("Interictal mean DeltaPhi_smooth:", interictal_smooth_mean)

print("\n===== BESTER THRESHOLD: LATE PREICTAL (5-10) VS INTERICTAL =====")
print(best_late)

print("\n===== KURZCHECK LATE PREICTAL =====")
print(df_late["y"].value_counts())
print(df_pre_only["preictal_bin"].value_counts().sort_index())

# =========================================
# MEMORY UPGRADE TEST
# Gleiche Features, gleiche Daten,
# nur stärkerer langsamer Memory-Term
# =========================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def add_memory_integral(df, decay=0.95):
    df = df.sort_values(["file", "center_s"]).copy()
    memory_values = []

    for file_name, sub in df.groupby("file"):
        J = 0.0
        for _, row in sub.iterrows():
            J = decay * J + row["DeltaPhi"]
            memory_values.append((row.name, J))

    memory_series = pd.Series(index=df.index, dtype=float)
    for idx, val in memory_values:
        memory_series.loc[idx] = val

    df["J_memory"] = memory_series.sort_index()
    return df

# Auf beide Dateien anwenden
df_mem_03 = add_memory_integral(df_feat_03, decay=0.95)
df_mem_04 = add_memory_integral(df_feat_04, decay=0.95)

# Combined
df_mem_combined = pd.concat([df_mem_03, df_mem_04], ignore_index=True)

print("Memory-Test vorbereitet.")
print(df_mem_combined[["file", "center_s", "label", "DeltaPhi", "J_memory"]].head())

# =========================================
# PLOT: DELTAPHI VS MEMORY-TERM
# =========================================

for file_name, sub in df_mem_combined.groupby("file"):
    sub = sub.sort_values("center_s")

    plt.figure(figsize=(14, 5))
    plt.plot(sub["center_s"], sub["DeltaPhi"], alpha=0.4, label="ΔΦ raw")
    plt.plot(sub["center_s"], sub["J_memory"], linewidth=2, label="J_memory")

    if file_name == "chb03_03":
        plt.axvspan(seizure_start_03, seizure_end_03, alpha=0.25, label="ictal")
    elif file_name == "chb03_04":
        plt.axvspan(seizure_start_04, seizure_end_04, alpha=0.25, label="ictal")

    plt.xlabel("Zeit (Sekunden)")
    plt.ylabel("Wert")
    plt.title(f"ΔΦ vs J_memory ({file_name})")
    plt.legend()
    plt.grid(True)
    plt.show()

# =========================================
# LATE PREICTAL (5-10 MIN) VS INTERICTAL
# MIT J_memory STATT DeltaPhi_smooth
# =========================================

def add_minutes_before_seizure(df, seizure_start, file_name):
    df = df.copy()
    df["file"] = file_name
    df["center_s"] = 0.5 * (df["win_start_s"] + df["win_end_s"])
    df["minutes_before_seizure"] = (seizure_start - df["center_s"]) / 60.0
    return df

dfp03 = add_minutes_before_seizure(df_mem_03, seizure_start_03, "chb03_03")
dfp04 = add_minutes_before_seizure(df_mem_04, seizure_start_04, "chb03_04")

dfp = pd.concat([dfp03, dfp04], ignore_index=True)
dfp = dfp[dfp["label"].isin(["preictal", "interictal_candidate"])].copy()

bins = [5, 10, 15, 20, 25, 30]
labels = ["5-10", "10-15", "15-20", "20-25", "25-30"]

dfp["preictal_bin"] = pd.cut(
    dfp["minutes_before_seizure"],
    bins=bins,
    labels=labels,
    right=False
)

df_late_mem = dfp[
    (dfp["label"] == "interictal_candidate") |
    ((dfp["label"] == "preictal") & (dfp["preictal_bin"] == "5-10"))
].copy()

df_late_mem["y"] = (
    (df_late_mem["label"] == "preictal") & (df_late_mem["preictal_bin"] == "5-10")
).astype(int)

print("Late-preictal vs interictal (memory-term):")
print(df_late_mem["y"].value_counts())

thresholds_mem = np.linspace(df_late_mem["J_memory"].min(), df_late_mem["J_memory"].max(), 50)

results_mem = []

for t in thresholds_mem:
    preds = (df_late_mem["J_memory"] > t).astype(int)

    TP = np.sum((preds == 1) & (df_late_mem["y"] == 1))
    TN = np.sum((preds == 0) & (df_late_mem["y"] == 0))
    FP = np.sum((preds == 1) & (df_late_mem["y"] == 0))
    FN = np.sum((preds == 0) & (df_late_mem["y"] == 1))

    sensitivity = TP / (TP + FN + 1e-9)
    specificity = TN / (TN + FP + 1e-9)

    results_mem.append((t, sensitivity, specificity))

df_mem_results = pd.DataFrame(results_mem, columns=["threshold", "sensitivity", "specificity"])
df_mem_results["score"] = df_mem_results["sensitivity"] + df_mem_results["specificity"]

best_mem = df_mem_results.loc[df_mem_results["score"].idxmax()]

print("\n===== BESTER THRESHOLD: J_memory (5-10) VS INTERICTAL =====")
print(best_mem)

# =========================================
# PREICTAL-BINS MIT J_memory
# =========================================

df_pre_only_mem = dfp[dfp["label"] == "preictal"].copy()

summary_mem_bins = df_pre_only_mem.groupby("preictal_bin")[["J_memory"]].agg(
    ["count", "mean", "std", "median", "max"]
)

interictal_mem_mean = dfp[dfp["label"] == "interictal_candidate"]["J_memory"].mean()

print("\n===== PREICTAL-BINS: J_memory =====")
print(summary_mem_bins)

print("\nInterictal mean J_memory:", interictal_mem_mean)

mem_bin_means = df_pre_only_mem.groupby("preictal_bin")["J_memory"].mean().reindex(labels)

plt.figure(figsize=(10, 5))
plt.plot(labels, mem_bin_means.values, marker="o", label="Preictal mean J_memory")
plt.axhline(interictal_mem_mean, linestyle="--", label="Interictal mean J_memory")
plt.xlabel("Minuten vor Anfall")
plt.ylabel("J_memory")
plt.title("Preictal J_memory nach Abstand zum Anfall")
plt.legend()
plt.grid(True)
plt.show()

df_feat_04, summary_04, roc_04, best_04 = run_same_pipeline(
    edf_path=edf_04,
    seizure_start=seizure_start_04,
    seizure_end=seizure_end_04,
    file_tag="chb03_04"
)

# =========================================
# ALLE WICHTIGEN ERGEBNISSE SPEICHERN
# =========================================

import os
import pandas as pd

output_dir = "/content/drive/MyDrive/CHB_MIT_DeltaPhi_Test/outputs/final_results"
os.makedirs(output_dir, exist_ok=True)

# Einzeldateien
df_feat_03.to_csv(f"{output_dir}/df_feat_03.csv", index=False)
df_feat_04.to_csv(f"{output_dir}/df_feat_04.csv", index=False)

# Combined
df_combined.to_csv(f"{output_dir}/df_combined.csv", index=False)

# Memory
df_mem_03.to_csv(f"{output_dir}/df_mem_03.csv", index=False)
df_mem_04.to_csv(f"{output_dir}/df_mem_04.csv", index=False)
df_mem_combined.to_csv(f"{output_dir}/df_mem_combined.csv", index=False)

# Tabellen speichern
summary_03.to_csv(f"{output_dir}/summary_03.csv")
summary_04.to_csv(f"{output_dir}/summary_04.csv")
summary_combined.to_csv(f"{output_dir}/summary_combined.csv")
summary_pre_bins.to_csv(f"{output_dir}/summary_pre_bins.csv")
summary_mem_bins.to_csv(f"{output_dir}/summary_mem_bins.csv")

# Threshold-Ergebnisse speichern
roc_03.to_csv(f"{output_dir}/roc_03.csv", index=False)
roc_04.to_csv(f"{output_dir}/roc_04.csv", index=False)
roc_combined.to_csv(f"{output_dir}/roc_combined.csv", index=False)
df_late_results.to_csv(f"{output_dir}/late_preictal_results.csv", index=False)
df_mem_results.to_csv(f"{output_dir}/memory_results.csv", index=False)

# Kurzprotokoll als Text
with open(f"{output_dir}/final_summary.txt", "w", encoding="utf-8") as f:
    f.write("CHB-MIT DeltaPhi Final Summary\n")
    f.write("==============================\n\n")

    f.write("chb03_03\n")
    f.write(summary_03.to_string())
    f.write("\n\n")
    f.write(str(best_03))
    f.write("\n\n")

    f.write("chb03_04\n")
    f.write(summary_04.to_string())
    f.write("\n\n")
    f.write(str(best_04))
    f.write("\n\n")

    f.write("combined\n")
    f.write(summary_combined.to_string())
    f.write("\n\n")
    f.write(str(best_combined))
    f.write("\n\n")

    f.write("Preictal bins (DeltaPhi)\n")
    f.write(summary_pre_bins.to_string())
    f.write("\n\n")
    f.write(f"Interictal mean DeltaPhi: {interictal_mean}\n")
    f.write(f"Interictal mean DeltaPhi_smooth: {interictal_smooth_mean}\n\n")

    f.write("Late preictal (5-10) vs interictal\n")
    f.write(str(best_late))
    f.write("\n\n")

    f.write("Preictal bins (J_memory)\n")
    f.write(summary_mem_bins.to_string())
    f.write("\n\n")
    f.write(f"Interictal mean J_memory: {interictal_mem_mean}\n")
    f.write("\n\n")
    f.write("Late preictal vs interictal (J_memory)\n")
    f.write(str(best_mem))
    f.write("\n")

print("Alle finalen Ergebnisse gespeichert unter:")
print(output_dir)

"""Auch scheinbar schwache oder unerwartete Ergebnisse sind relevant,
da sie auf mögliche Modellgrenzen oder zusätzliche Dynamiken hinweisen.

In diesem Sinne stellen sie keinen Fehler dar,
sondern einen Ausgangspunkt für weiterführende Analysen.
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mne


def shannon_entropy_1d(x, bins=64):
    x = np.asarray(x).ravel()
    hist, _ = np.histogram(x, bins=bins, density=True)
    hist = hist[hist > 0]
    if len(hist) == 0:
        return 0.0
    p = hist / hist.sum()
    return -np.sum(p * np.log(p + 1e-12))


def compute_window_features(window_data):
    channel_vars = np.var(window_data, axis=1)
    channel_ranges = np.ptp(window_data, axis=1)
    S = 0.5 * np.mean(channel_vars) + 0.5 * np.mean(channel_ranges)

    entropies = [shannon_entropy_1d(ch, bins=64) for ch in window_data]
    I = np.mean(entropies)

    corr = np.corrcoef(window_data)
    corr = np.nan_to_num(corr, nan=0.0)
    upper = corr[np.triu_indices_from(corr, k=1)]
    C = np.mean(np.abs(upper))

    return S, I, C


def run_pipeline(edf_path, seizure_start, seizure_end, file_tag, output_dir="outputs"):
    raw = mne.io.read_raw_edf(edf_path, preload=True, verbose=False)

    sfreq = raw.info["sfreq"]
    duration_sec = raw.n_times / sfreq
    window_sec = 10

    windows = []
    for start in np.arange(0, duration_sec, window_sec):
        end = min(start + window_sec, duration_sec)
        windows.append((float(start), float(end)))

    df_windows = pd.DataFrame(windows, columns=["win_start_s", "win_end_s"])

    SOP = 30 * 60
    SPH = 5 * 60
    POST = 30 * 60

    def label_window(row):
        center = (row["win_start_s"] + row["win_end_s"]) / 2

        if seizure_start <= center < seizure_end:
            return "ictal"

        if (seizure_start - SOP) <= center < (seizure_start - SPH):
            return "preictal"

        if seizure_end <= center < (seizure_end + POST):
            return "exclude"

        return "interictal_candidate"

    df_windows["label"] = df_windows.apply(label_window, axis=1)
    df_use = df_windows[df_windows["label"].isin(["preictal", "ictal", "interictal_candidate"])].copy()

    rows = []
    for _, row in df_use.iterrows():
        start_sample = int(row["win_start_s"] * sfreq)
        end_sample = int(row["win_end_s"] * sfreq)
        segment = raw.get_data(start=start_sample, stop=end_sample)

        S, I, C = compute_window_features(segment)

        rows.append({
            "file": file_tag,
            "win_start_s": row["win_start_s"],
            "win_end_s": row["win_end_s"],
            "label": row["label"],
            "S": S,
            "I": I,
            "C": C
        })

    df_feat = pd.DataFrame(rows)

    baseline_df = df_feat[df_feat["label"] == "interictal_candidate"].copy()
    baseline_S = baseline_df["S"].mean()
    baseline_I = baseline_df["I"].mean()
    baseline_C = baseline_df["C"].mean()

    ALPHA = 0.40
    BETA = 0.35
    GAMMA = 0.25

    df_feat["dS"] = df_feat["S"] - baseline_S
    df_feat["dI"] = df_feat["I"] - baseline_I
    df_feat["dC"] = df_feat["C"] - baseline_C

    df_feat["DeltaPhi"] = (
        ALPHA * np.abs(df_feat["dS"]) +
        BETA * np.abs(df_feat["dI"]) +
        GAMMA * np.abs(df_feat["dC"])
    )

    df_feat["center_s"] = 0.5 * (df_feat["win_start_s"] + df_feat["win_end_s"])
    df_feat["DeltaPhi_smooth"] = df_feat["DeltaPhi"].rolling(5, min_periods=1).mean()

    os.makedirs(output_dir, exist_ok=True)
    csv_path = os.path.join(output_dir, f"{file_tag}_features.csv")
    df_feat.to_csv(csv_path, index=False)

    return df_feat


if __name__ == "__main__":
    print("CHB-MIT DeltaPhi pipeline ready.")
    print("Passe hier die Dateipfade und seizure-Zeiten an.")

file_path = "/content/drive/MyDrive/CHB-MIT-DeltaPhi-Test-CLEAN/src/chb_mit_delta_phi_pipeline.py"

code = """import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mne


def shannon_entropy_1d(x, bins=64):
    x = np.asarray(x).ravel()
    hist, _ = np.histogram(x, bins=bins, density=True)
    hist = hist[hist > 0]
    if len(hist) == 0:
        return 0.0
    p = hist / hist.sum()
    return -np.sum(p * np.log(p + 1e-12))


def compute_window_features(window_data):
    channel_vars = np.var(window_data, axis=1)
    channel_ranges = np.ptp(window_data, axis=1)
    S = 0.5 * np.mean(channel_vars) + 0.5 * np.mean(channel_ranges)

    entropies = [shannon_entropy_1d(ch, bins=64) for ch in window_data]
    I = np.mean(entropies)

    corr = np.corrcoef(window_data)
    corr = np.nan_to_num(corr, nan=0.0)
    upper = corr[np.triu_indices_from(corr, k=1)]
    C = np.mean(np.abs(upper))

    return S, I, C


def run_pipeline(edf_path, seizure_start, seizure_end, file_tag, output_dir="outputs"):
    raw = mne.io.read_raw_edf(edf_path, preload=True, verbose=False)

    sfreq = raw.info["sfreq"]
    duration_sec = raw.n_times / sfreq
    window_sec = 10

    windows = []
    for start in np.arange(0, duration_sec, window_sec):
        end = min(start + window_sec, duration_sec)
        windows.append((float(start), float(end)))

    df_windows = pd.DataFrame(windows, columns=["win_start_s", "win_end_s"])

    SOP = 30 * 60
    SPH = 5 * 60
    POST = 30 * 60

    def label_window(row):
        center = (row["win_start_s"] + row["win_end_s"]) / 2

        if seizure_start <= center < seizure_end:
            return "ictal"

        if (seizure_start - SOP) <= center < (seizure_start - SPH):
            return "preictal"

        if seizure_end <= center < (seizure_end + POST):
            return "exclude"

        return "interictal_candidate"

    df_windows["label"] = df_windows.apply(label_window, axis=1)
    df_use = df_windows[df_windows["label"].isin(["preictal", "ictal", "interictal_candidate"])].copy()

    rows = []
    for _, row in df_use.iterrows():
        start_sample = int(row["win_start_s"] * sfreq)
        end_sample = int(row["win_end_s"] * sfreq)
        segment = raw.get_data(start=start_sample, stop=end_sample)

        S, I, C = compute_window_features(segment)

        rows.append({
            "file": file_tag,
            "win_start_s": row["win_start_s"],
            "win_end_s": row["win_end_s"],
            "label": row["label"],
            "S": S,
            "I": I,
            "C": C
        })

    df_feat = pd.DataFrame(rows)

    baseline_df = df_feat[df_feat["label"] == "interictal_candidate"].copy()
    baseline_S = baseline_df["S"].mean()
    baseline_I = baseline_df["I"].mean()
    baseline_C = baseline_df["C"].mean()

    ALPHA = 0.40
    BETA = 0.35
    GAMMA = 0.25

    df_feat["dS"] = df_feat["S"] - baseline_S
    df_feat["dI"] = df_feat["I"] - baseline_I
    df_feat["dC"] = df_feat["C"] - baseline_C

    df_feat["DeltaPhi"] = (
        ALPHA * np.abs(df_feat["dS"]) +
        BETA * np.abs(df_feat["dI"]) +
        GAMMA * np.abs(df_feat["dC"])
    )

    df_feat["center_s"] = 0.5 * (df_feat["win_start_s"] + df_feat["win_end_s"])
    df_feat["DeltaPhi_smooth"] = df_feat["DeltaPhi"].rolling(5, min_periods=1).mean()

    os.makedirs(output_dir, exist_ok=True)
    save_path = os.path.join(output_dir, f"{file_tag}_features.csv")
    df_feat.to_csv(save_path, index=False)

    print(f"Gespeichert: {save_path}")

    return df_feat


if __name__ == "__main__":
    print("Pipeline bereit.")
    print("Beispiel-Aufruf unten aktivieren.")

    # Beispiel:
    # run_pipeline("data/chb03_03.edf", 432, 501, "chb03_03")
"""
with open(file_path, "w") as f:
    f.write(code)

print("CLEAN VERSION ERSETZT!")

import os
import sys

project_root = "/content/drive/MyDrive/CHB-MIT-DeltaPhi-Test-CLEAN"
src_path = os.path.join(project_root, "src")
data_path = os.path.join(project_root, "data")
outputs_path = os.path.join(project_root, "outputs")

sys.path.append(src_path)

from chb_mit_delta_phi_pipeline import run_pipeline

df_test = run_pipeline(
    edf_path=os.path.join(data_path, "chb03_03.edf"),
    seizure_start=432,
    seizure_end=501,
    file_tag="chb03_03_test",
    output_dir=outputs_path
)

print(df_test.head())
print("Anzahl Zeilen:", len(df_test))

req_path = "/content/drive/MyDrive/CHB-MIT-DeltaPhi-Test-CLEAN/requirements.txt"

req_text = """numpy
pandas
matplotlib
mne
"""

with open(req_path, "w", encoding="utf-8") as f:
    f.write(req_text)

print("requirements.txt erstellt.")

gitignore_path = "/content/drive/MyDrive/CHB-MIT-DeltaPhi-Test-CLEAN/.gitignore"

gitignore_text = """__pycache__/
*.pyc
.ipynb_checkpoints/
outputs/
*.csv
"""

with open(gitignore_path, "w", encoding="utf-8") as f:
    f.write(gitignore_text)

print(".gitignore erstellt.")

readme_path = "/content/drive/MyDrive/CHB-MIT-DeltaPhi-Test-CLEAN/README.md"

readme_text = '''
# CHB-MIT DeltaPhi Test

This project explores whether a composite marker called **DeltaPhi (ΔΦ)** can capture changes in EEG dynamics before epileptic seizures.

## Core idea

DeltaPhi combines three components:

- **S (Structure):** signal geometry based on variance and range
- **I (Information):** Shannon entropy
- **C (Coupling):** mean absolute inter-channel correlation

These components are compared to an interictal baseline and combined into a single score:

ΔΦ = α|dS| + β|dI| + γ|dC|

with:

- α = 0.40
- β = 0.35
- γ = 0.25

## Project structure

    CHB-MIT-DeltaPhi-Test-CLEAN/
    ├── data/
    │   ├── chb03_03.edf
    │   └── chb03_04.edf
    ├── docs/
    ├── outputs/
    ├── src/
    │   └── chb_mit_delta_phi_pipeline.py
    ├── requirements.txt
    ├── .gitignore
    └── README.md

## Installation

    pip install -r requirements.txt

## Example usage

    from src.chb_mit_delta_phi_pipeline import run_pipeline

    df = run_pipeline(
        edf_path="data/chb03_03.edf",
        seizure_start=432,
        seizure_end=501,
        file_tag="chb03_03",
        output_dir="outputs"
    )

## Current test files

- `chb03_03.edf`
  - seizure start: 432 s
  - seizure end: 501 s

- `chb03_04.edf`
  - seizure start: 2162 s
  - seizure end: 2214 s

## Notes

This repository is a research-style exploratory pipeline, not a clinical diagnostic tool.

The goal is to test whether ΔΦ provides interpretable signal changes across interictal, preictal, and ictal windows.
'''

with open(readme_path, "w", encoding="utf-8") as f:
    f.write(readme_text)

print("README.md erstellt.")

req_path = "/content/drive/MyDrive/CHB-MIT-DeltaPhi-Test-CLEAN/requirements.txt"

req_text = """numpy
pandas
matplotlib
mne
"""

with open(req_path, "w", encoding="utf-8") as f:
    f.write(req_text)

print("requirements.txt erstellt.")

gitignore_path = "/content/drive/MyDrive/CHB-MIT-DeltaPhi-Test-CLEAN/.gitignore"

gitignore_text = """__pycache__/
*.pyc
.ipynb_checkpoints/
outputs/
*.csv
"""

with open(gitignore_path, "w", encoding="utf-8") as f:
    f.write(gitignore_text)

print(".gitignore erstellt.")